import {
  DocCards,
  DocCta,
  DocHero,
  DocNav,
  DocNote,
  DocSectionBlock,
  SpecTable,
  type DocSection,
} from './DocKit';

const SECTIONS: DocSection[] = [
  { id: 'can', label: 'What it does' },
  { id: 'cannot', label: 'What it does not do' },
  { id: 'risk-model', label: 'Risk model' },
  { id: 'attribution', label: 'Attribution' },
];

/**
 * Capabilities.
 *
 * Structured around the boundary rather than the feature list. A capability page that
 * only lists what a system can do is marketing; the half that matters to an
 * investigator is knowing what it will not claim, so that section comes second and is
 * written as plainly as the first.
 */
export default function Capabilities() {

  return (
    <>
      <DocHero
        eyebrow="Capabilities"
        title="What the service can show you, and what it will not claim."
        lede="Fund-flow tracing, entity attribution and transparent risk scoring on public blockchains. The limits are stated here rather than discovered during an investigation, because a tool that overstates its reach is worse than one that has none."
      />

      <DocNav sections={SECTIONS} />

      <DocSectionBlock id="can" title="What it does">
        <DocCards
          cards={[
            {
              title: 'Traces fund flow from one address',
              body: 'Collects native and token transfers outward from a submitted wallet, bounded by a hop depth, a per-address fan-out and a node budget.',
            },
            {
              title: 'Resolves addresses to entities',
              body: 'Matches counterparties against a curated registry, provider labels and on-chain contract naming, and reports how confident each match is.',
            },
            {
              title: 'Scores observable risk signals',
              body: 'Weights mixing, sanction exposure, cash-out to exchanges, fan-out, convergence and layering, then returns the raw factors next to the score.',
            },
            {
              title: 'Explains a single transfer',
              body: 'Every edge carries its amount, asset, transaction hash and timestamp, so a conclusion can be walked back to the transfer that produced it.',
            },
            {
              title: 'Renders a service-owned report',
              body: 'The report is generated by the backend from the stored trace, so the exported artefact and the screen describe the same investigation.',
            },
            {
              title: 'Reads both supported chains',
              body: 'Ethereum and Tron are traced independently against their own indexers, with per-chain results and a worst-case summary.',
            },
          ]}
        />
      </DocSectionBlock>

      <DocSectionBlock id="cannot" title="What it does not do">
        <DocCards
          cards={[
            {
              title: 'It does not identify a person',
              body: 'Attribution resolves an address to an entity or to nothing. Ownership of a wallet is not established, and a label is a claim about an address, not about a person or a business.',
            },
            {
              title: 'It does not declare fraud or crime',
              body: 'The output is a risk indicator derived from observable behaviour. It is a triage aid for a human reviewer, not a determination of wrongdoing.',
            },
            {
              title: 'It does not trace across chains',
              body: 'A multi-chain request runs per chain and reports the results side by side. No transfer between an Ethereum address and a Tron address is inferred, because none is observable.',
            },
            {
              title: 'It does not cover private or unindexed activity',
              body: 'Coverage is limited to what the chain indexer returns within the configured limits. Anything the indexer does not carry is invisible to the service.',
            },
            {
              title: 'It does not produce a complete history',
              body: 'The trace is a bounded subgraph. An address can have activity beyond the depth and fan-out limits, and that activity is absent by design rather than by failure.',
            },
            {
              title: 'It does not act on your behalf',
              body: 'No funds are moved, no transactions are signed and no cases are reported to any authority. The service produces evidence for a human decision.',
            },
          ]}
        />
        <DocNote>
          Every figure shown on the marketing site that is not a live trace result is
          illustrative and labelled as such. Figures taken from a real trace always come from
          the investigation service.
        </DocNote>
      </DocSectionBlock>

      <DocSectionBlock id="risk-model" title="The risk model">
        <p>
          Signals are weighted independently, summed, capped at 100 and mapped to a category.
          The weights and thresholds below are the ones the backend applies, and the same
          table is reproduced in the workstation so an investigator can read the arithmetic
          behind a score rather than trusting it.
        </p>
        <SpecTable
          rows={[
            ['Reported wallet is itself sanctioned', '+40'],
            ['Sanctioned address downstream', '+45'],
            ['Mixer or tumbler downstream', '+45'],
            ['Cash-out at a labelled exchange or VASP deposit address', '+15'],
            ['Layering — path spans 3+ hops before any cash-out point', '+20'],
            ['High fan-out — funds split across 5+ destinations', '+15'],
            ['Convergence — 3+ distinct sources fund one wallet', '+10'],
            ['Cap', 'Raw totals are capped at 100'],
            ['LOW', 'Below 25'],
            ['MEDIUM', '25 to 49'],
            ['HIGH', '50 to 74'],
            ['CRITICAL', '75 and above'],
          ]}
        />
        <p>
          A score of zero is not an all-clear. It means no weighted rule fired on the subgraph
          that was traced, which is a much weaker statement.
        </p>
      </DocSectionBlock>

      <DocSectionBlock id="attribution" title="How attribution resolves">
        <p>
          Each address is resolved in a fixed order, and the first source to produce a label
          wins:
        </p>
        <SpecTable
          rows={[
            ['1', 'Cached resolution from an earlier trace in this deployment'],
            ['2', 'Curated entity registry — known exchanges, mixers and sanctioned addresses'],
            ['3', 'Provider labels attached to the address by the chain data provider'],
            ['4', 'On-chain contract-name heuristics, used only as a last resort'],
            ['No match', 'The address stays unlabelled, and the interface says so'],
          ]}
        />
        <p>
          Every resolution carries a confidence value. Heuristic contract names in particular
          can be wrong, which is why they sit last and why the confidence is shown next to the
          label rather than buried in the record.
        </p>
      </DocSectionBlock>

      <DocCta />
    </>
  );
}
