spring.datasource.url=jdbc:postgresql://localhost:5432/cryptofraud
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=cryptofraud
spring.datasource.password=cryptofraud
spring.h2.console.enabled=false
